In [1]:
# import dependencies
import pandas as pd
from apiKey import api_key
import requests
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress

In [13]:
file_one = "Output/Movie_Data.csv"
data_df = pd.read_csv(file_one)
data_df.head(12)

,Unnamed: 0,Title,World Sales,Year Released,Rotten Tomatoes Score,IMDB Score,Director(s),Headlining Actor(s),Studio,Runtime,Rating,Genre
0,0,Star Wars: Episode VII - The Force Awakens,2069521700,2015,93%,7.80,J.J. Abrams,"Daisy Ridley, John Boyega, Oscar Isaac",Walt Disney Studios Motion Pictures,138 min,PG-13,"['Action', 'Adventure', 'Sci-Fi']"
1,1,Avengers: Endgame,2797501328,2019,94%,8.40,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Evans, Mark Ruffalo",Walt Disney Studios Motion Pictures,181 min,PG-13,"['Action', 'Adventure', 'Drama', 'Sci-Fi']"
2,2,Avatar,2847246203,2009,82%,7.90,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver",Twentieth Century Fox,162 min,PG-13,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']"
3,3,Black Panther,1347597973,2018,96%,7.30,Ryan Coogler,"Chadwick Boseman, Michael B. Jordan, Lupita Ny...",Walt Disney Studios Motion Pictures,134 min,PG-13,"['Action', 'Adventure', 'Sci-Fi']"
4,4,Avengers: Infinity War,2048359754,2018,85%,8.40,"Anthony Russo, Joe Russo","Robert Downey Jr., Chris Hemsworth, Mark Ruffalo",Walt Disney Studios Motion Pictures,149 min,PG-13,"['Action', 'Adventure', 'Sci-Fi']"
5,5,Spider-Man: No Way Home,1544455963,2021,93%,8.20,Jon Watts,"Tom Holland, Zendaya, Benedict Cumberbatch",Sony Pictures Entertainment (SPE),148 min,PG-13,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']"
6,6,Titanic,2201647264,1997,88%,7.90,James Cameron,"Leonardo DiCaprio, Kate Winslet, Billy Zane",Paramount Pictures,194 min,PG-13,"['Drama', 'Romance']"
7,7,Jurassic World,1670516444,2015,71%,6.90,Colin Trevorrow,"Chris Pratt, Bryce Dallas Howard, Ty Simpkins",Universal Pictures,124 min,PG-13,"['Action', 'Adventure', 'Sci-Fi']"
8,8,The Avengers,1518815515,2012,91%,8.00,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",Walt Disney Studios Motion Pictures,143 min,PG-13,"['Action', 'Adventure', 'Sci-Fi']"
9,9,Star Wars: Episode VIII - The Last Jedi,1332698830,2017,91%,6.90,Rian Johnson,"Daisy Ridley, John Boyega, Mark Hamill",Walt Disney Studios Motion Pictures,152 min,PG-13,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']"
10,10,Incredibles 2,1243089244,2018,93%,7.60,Brad Bird,"Craig T. Nelson, Holly Hunter, Sarah Vowell",Walt Disney Studios Motion Pictures,118 min,PG,"['Action', 'Adventure', 'Animation', 'Comedy',..."
11,11,The Lion King,1662899439,1994,93%,8.50,"Roger Allers, Rob Minkoff","Matthew Broderick, Jeremy Irons, James Earl Jones",Walt Disney Studios Motion Pictures,88 min,G,"['Adventure', 'Animation', 'Drama', 'Family', ..."

In [14]:
dir_top_earning_df = pd.DataFrame()
dir_top_earning_df['Director(s)'] = data_df['Director(s)']
dir_top_earning_df['World Sales'] = data_df['World Sales']
dir_top_earning_df['Title'] = data_df['Title']
dir_top_earning_df['Year Released'] = data_df['Year Released']
dir_top_earning_df = dir_top_earning_df.sort_values(by=['World Sales'], ascending=False)

In [5]:
dir_ls = data_df["Director(s)"].unique()
#dir_ls
dir_df = data_df.groupby("Director(s)").agg(world_sales_sum=('World Sales','sum'),world_sales_mean=('World Sales','mean'),total_number_films=('Title','count'))    #{'World Sales':["sum","mean"], 'Title':"count"}
#dir_df = dir_df.reset_index()
dir_df = dir_df.rename(columns={'world_sales_sum':"World Sales Sum", 'world_sales_mean':"World Sales Mean", 'total_number_films':"Total Number of Films in Top 1000"})
dir_sum_df = dir_df.sort_values(by=['World Sales Sum'], ascending=False)
dir_mean_df = dir_df.sort_values(by=['World Sales Mean'], ascending=False)
dir_num_df = dir_df.sort_values(by=['Total Number of Films in Top 1000'], ascending=False)
#dir_df["Director Average World Gross per Film"] = (dir_df['World Sales']/dir_df['Title'])
#dir_df.head(10)
#dir_sum_df.dtypes
pd.options.display.float_format = '{:.2f}'.format

In [6]:
dir_sum_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Director(s),,,
Steven Spielberg,7204613848,514615274.86,14
"Anthony Russo, Joe Russo",6713620081,1678405020.25,4
Peter Jackson,6486316403,926616629.00,7
David Yates,6026723942,860960563.14,7
James Cameron,5753123050,1438280762.50,4
Michael Bay,5564785117,618309457.44,9
J.J. Abrams,4579054666,763175777.67,6
Christopher Nolan,4526360683,754393447.17,6
Justin Lin,3603943765,600657294.17,6
Jon Watts,3556550883,1185516961.00,3

In [7]:
dir_mean_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Director(s),,,
"Anthony Russo, Joe Russo",6713620081,1678405020.25,4
Colin Trevorrow,1670516444,1670516444.00,1
Joss Whedon,2921625055,1460812527.50,2
James Cameron,5753123050,1438280762.50,4
"Chris Buck, Jennifer Lee",2731535033,1365767516.50,2
"Roger Allers, Rob Minkoff",2726511244,1363255622.00,2
Ryan Coogler,1347597973,1347597973.00,1
J.A. Bayona,1310466296,1310466296.00,1
Shane Black,1214811252,1214811252.00,1
Jon Watts,3556550883,1185516961.00,3

In [8]:
dir_num_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Director(s),,,
Steven Spielberg,7204613848,514615274.86,14
Michael Bay,5564785117,618309457.44,9
Ron Howard,2954745200,422106457.14,7
David Yates,6026723942,860960563.14,7
Peter Jackson,6486316403,926616629.00,7
Robert Zemeckis,2703659217,386237031.00,7
J.J. Abrams,4579054666,763175777.67,6
Justin Lin,3603943765,600657294.17,6
Christopher Nolan,4526360683,754393447.17,6
Bryan Singer,3295921385,549320230.83,6

In [25]:
dir_top_earning_df.head(10)

,Director(s),World Sales,Title,Year Released
2,James Cameron,2847246203,Avatar,2009
1,"Anthony Russo, Joe Russo",2797501328,Avengers: Endgame,2019
6,James Cameron,2201647264,Titanic,1997
0,J.J. Abrams,2069521700,Star Wars: Episode VII - The Force Awakens,2015
4,"Anthony Russo, Joe Russo",2048359754,Avengers: Infinity War,2018
7,Colin Trevorrow,1670516444,Jurassic World,2015
11,"Roger Allers, Rob Minkoff",1662899439,The Lion King,1994
5,Jon Watts,1544455963,Spider-Man: No Way Home,2021
8,Joss Whedon,1518815515,The Avengers,2012
54,James Wan,1515341399,Furious 7,2015

In [26]:
stu_top_earning_df = pd.DataFrame()
stu_top_earning_df['Studio'] = data_df['Studio']
stu_top_earning_df['World Sales'] = data_df['World Sales']
stu_top_earning_df['Title'] = data_df['Title']
stu_top_earning_df['Year Released'] = data_df['Year Released']
stu_top_earning_df = stu_top_earning_df.sort_values(by=['World Sales'], ascending=False)

In [27]:
stu_ls = data_df["Studio"].unique()

stu_df = data_df.groupby("Studio").agg(world_sales_sum=('World Sales','sum'),world_sales_mean=('World Sales','mean'),total_number_films=('Title','count'))    

stu_df = stu_df.rename(columns={'world_sales_sum':"World Sales Sum", 'world_sales_mean':"World Sales Mean", 'total_number_films':"Total Number of Films in Top 1000"})
stu_sum_df = stu_df.sort_values(by=['World Sales Sum'], ascending=False)
stu_mean_df = stu_df.sort_values(by=['World Sales Mean'], ascending=False)
stu_num_df = stu_df.sort_values(by=['Total Number of Films in Top 1000'], ascending=False)


pd.options.display.float_format = '{:.2f}'.format

In [28]:
stu_sum_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Studio,,,
Walt Disney Studios Motion Pictures,71414021614,707069520.93,101
Warner Bros.,45953080269,553651569.51,83
Twentieth Century Fox,36698425510,516879232.54,71
Universal Pictures,33698979597,510590599.95,66
Sony Pictures Entertainment (SPE),26580973445,542468845.82,49
Paramount Pictures,22556436985,479924191.17,47
DreamWorks,8977094378,641221027.00,14
Lionsgate,5782746831,525704257.36,11
New Line Cinema,5411878466,450989872.17,12
DreamWorks Distribution,4530172417,453017241.70,10

In [29]:
stu_mean_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Studio,,,
Walt Disney Studios Motion Pictures,71414021614,707069520.93,101
DreamWorks,8977094378,641221027.00,14
Summit Entertainment,2530153099,632538274.75,4
Newmarket Films,612054506,612054506.00,1
Warner Bros.,45953080269,553651569.51,83
Sony Pictures Entertainment (SPE),26580973445,542468845.82,49
Lionsgate,5782746831,525704257.36,11
Twentieth Century Fox,36698425510,516879232.54,71
Universal Pictures,33698979597,510590599.95,66
Paramount Pictures,22556436985,479924191.17,47

In [30]:
stu_num_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Studio,,,
Walt Disney Studios Motion Pictures,71414021614,707069520.93,101
Warner Bros.,45953080269,553651569.51,83
Twentieth Century Fox,36698425510,516879232.54,71
Universal Pictures,33698979597,510590599.95,66
Sony Pictures Entertainment (SPE),26580973445,542468845.82,49
Paramount Pictures,22556436985,479924191.17,47
DreamWorks,8977094378,641221027.00,14
New Line Cinema,5411878466,450989872.17,12
Lionsgate,5782746831,525704257.36,11
DreamWorks Distribution,4530172417,453017241.70,10

In [22]:
stu_top_earning_df.head(10)

,Studio,World Sales,Title,Year Released
2,Twentieth Century Fox,2847246203,Avatar,2009
1,Walt Disney Studios Motion Pictures,2797501328,Avengers: Endgame,2019
6,Paramount Pictures,2201647264,Titanic,1997
0,Walt Disney Studios Motion Pictures,2069521700,Star Wars: Episode VII - The Force Awakens,2015
4,Walt Disney Studios Motion Pictures,2048359754,Avengers: Infinity War,2018
7,Universal Pictures,1670516444,Jurassic World,2015
11,Walt Disney Studios Motion Pictures,1662899439,The Lion King,1994
5,Sony Pictures Entertainment (SPE),1544455963,Spider-Man: No Way Home,2021
8,Walt Disney Studios Motion Pictures,1518815515,The Avengers,2012
54,Universal Pictures,1515341399,Furious 7,2015

In [59]:
test_ls = []

for s in data_df[:2]:
    print(data_df["World Sales"].values)

[2069521700 2797501328 2847246203 1347597973 2048359754 1544455963
 2201647264 1670516444 1518815515 1332698830 1243089244 1662899439
 1005973645 1056057720 1074149279 1273576220 1028570942 1450026933
 1027082707  775398007 1402809540 1081142612  928760770  792910554
 1073394593 1128462972  865011746 1066179747 1063611805 1310466296
 1066970811  822824522 1214811252 1153337496  694394724  825025036
  962542945 1033928303  836303693 1281508100 1131927996  863756051
 1342321665  940352645  868390560 1146030912  788976453  612054506
  875458631  970766005  966554929  782836791  858848019 1050693953
 1515341399 1123794079  547426372  947495095 1024121104  755356711
  894983373 1159444662 1074419384 1148485886  880166924 1025468216
  773350147  678226133  873637528  701796444  746846894  785896609
  813367380  800059707  709709780  585796247 1016813075  790653942
  897690072  853983911  623933331  653779970  960996492  475106177
  817400891  654264015 1108569499 1017003568  934454096  698491347
  711025481  977043483  672806432  735099102  538375067  836836967
  942172396  829747654  745013115  668045518  579707738  896678241
  476684675  658344137  741847937  712205856  522657936  469310836
  723192705  512568819  634208384  743559645  487853320 1034800131
  879602366  757930663  631607053  471411300  345573032  714421503
  959007513  468060692  385680446  585410052  309208309  962182865
  586764305  543113985  411508343  574481229  589390539  797361618
  644136488  389925971  497375381 1104054072  461991867  296578797
  484592874  494471524  368744044  758411779 1045713802  752600867
  788680968  538983207  493311825  460435291  603873119  814044001
  746045700  429632142  441306145  677796076  618638999  657926987
  467365246  630162448  408247917  629443428  444100035  619179950
  347325802 1236005118  432233010  521311890  657869686  791657398
  459242249  443140005  441286195  424967620  549368315  556906378
  505703557  494879471  760006945  504050219  365352546  482349603
  910809311  622674139  746921274  631746197  546388108  436188866
  407711549  348840316  392924807  856085151  296938801  501138437
  473093228  381906762  456068181  807817888  626137675  694713380
  288467645  524028679  710644566  373661946  474968763  623726085
  644783140  426505244  312016928  520881154  708982323  540455876
  443280904  553709788  542358331  529323962  592462816  524976069
  391081192  880681519  449220945  381509870  384336108  474171806
  886686817  667094506  682716636  408430415  445135288  542063846
  331333876  559852396  485004754  375540831  396271103  527016307
  471222889  340952971  701729206  314215454  465380802  587235983
  543848418  552639571  487287646  184925486  287144079  424208848
  336567158  368875760  379631351  532950503  450717150  536414293
  374111707  328718434  275293450  302710615  368780809  449326618
  457696391  519311965  362211740  603900354  373062864  333107271
  371594210  624026776  463406268  386041607  413106170  177200000
  621537519  481800873  370569774  223853736  359126022  369884651
  383257136  290835269  311950384  255185482  527965936  238539198
  436949634  759056935  355237933  358994850  347512318  726229501
  315156409  354825435  794881442  400063852  349546142  466625730
  252276927  448191819  327281779  316791257  306776732  216639112
  475186706  235956898  288383523  589580482  253625427  566652812
  167780960  369330363  528583774  616502912  330444045  569651467
  791217826  390493908  311605581  665692281  351692268  401847482
  352114312  317375031  307127625  234801895  493214993  325186032
  266892996  426074373  363258859  415484914  271457301  185991646
  877244782  201634991  431971116  374583879  524389083  774034007
  297372261  229930771  654855901  255614941  384919389  430051293
  343471816  270248367  191466556  296339528  278019771  329803958
  291420351  543934105  415933406  396592829  474009154  360366870
  339795890  333535934  298572799  375658750  273552592  346864886
  275650703  383930656  418765519  309460292  448906865  288885818
  269994119  433371112  242786137  302469017  270665134  251171807
  554987477  319715683  442299309  219922417  314178011  310650585
  321885765  358375603  163362095  269958228  227853986  490719763
  352616690  183348429  378882411  273144151  190539357  530438278
  287553595  226837760  353642274  353133898  321731527  207305509
  611257819  294456605  433514834  483866518  521170825  232372681
  255743093  563749323  374565754  277448382  419665568  346079773
  243240178  378410542  244721064  248639099  349464664  365971656
  297718711  258097122  300135367  376152455  231605150  427344325
  172855065  427374317  190538630  273339556  138545632  201585328
  225933435  278454417  325286646  349822765  582893671  320290989
  240685326  286801374  309492681  379014294  232325503  195745823
  314432837  201965915  202292902  246120986  154468902  264770996
  388156011  342463063  173965010  300451603  335062621  398479497
  246984278  497409852  485930816  342695435  164729679  414828246
  306209289  291465373  245285165  236412453  358372926  301913131
  319713881  498781117  274703340  272742922  341631208  285444603
  230685453  297002527  246233113  605425157  269755430  356296601
  249348933  273961019  262552893  229147509  414351546  262511490
  213525736  294805697  212902372  300473716  340487836  335802786
  216972543  173649931  180622424  467989645  247275374  236350661
  299288605  260095986  361832400  227927165  458863600]
[2069521700 2797501328 2847246203 1347597973 2048359754 1544455963
 2201647264 1670516444 1518815515 1332698830 1243089244 1662899439
 1005973645 1056057720 1074149279 1273576220 1028570942 1450026933
 1027082707  775398007 1402809540 1081142612  928760770  792910554
 1073394593 1128462972  865011746 1066179747 1063611805 1310466296
 1066970811  822824522 1214811252 1153337496  694394724  825025036
  962542945 1033928303  836303693 1281508100 1131927996  863756051
 1342321665  940352645  868390560 1146030912  788976453  612054506
  875458631  970766005  966554929  782836791  858848019 1050693953
 1515341399 1123794079  547426372  947495095 1024121104  755356711
  894983373 1159444662 1074419384 1148485886  880166924 1025468216
  773350147  678226133  873637528  701796444  746846894  785896609
  813367380  800059707  709709780  585796247 1016813075  790653942
  897690072  853983911  623933331  653779970  960996492  475106177
  817400891  654264015 1108569499 1017003568  934454096  698491347
  711025481  977043483  672806432  735099102  538375067  836836967
  942172396  829747654  745013115  668045518  579707738  896678241
  476684675  658344137  741847937  712205856  522657936  469310836
  723192705  512568819  634208384  743559645  487853320 1034800131
  879602366  757930663  631607053  471411300  345573032  714421503
  959007513  468060692  385680446  585410052  309208309  962182865
  586764305  543113985  411508343  574481229  589390539  797361618
  644136488  389925971  497375381 1104054072  461991867  296578797
  484592874  494471524  368744044  758411779 1045713802  752600867
  788680968  538983207  493311825  460435291  603873119  814044001
  746045700  429632142  441306145  677796076  618638999  657926987
  467365246  630162448  408247917  629443428  444100035  619179950
  347325802 1236005118  432233010  521311890  657869686  791657398
  459242249  443140005  441286195  424967620  549368315  556906378
  505703557  494879471  760006945  504050219  365352546  482349603
  910809311  622674139  746921274  631746197  546388108  436188866
  407711549  348840316  392924807  856085151  296938801  501138437
  473093228  381906762  456068181  807817888  626137675  694713380
  288467645  524028679  710644566  373661946  474968763  623726085
  644783140  426505244  312016928  520881154  708982323  540455876
  443280904  553709788  542358331  529323962  592462816  524976069
  391081192  880681519  449220945  381509870  384336108  474171806
  886686817  667094506  682716636  408430415  445135288  542063846
  331333876  559852396  485004754  375540831  396271103  527016307
  471222889  340952971  701729206  314215454  465380802  587235983
  543848418  552639571  487287646  184925486  287144079  424208848
  336567158  368875760  379631351  532950503  450717150  536414293
  374111707  328718434  275293450  302710615  368780809  449326618
  457696391  519311965  362211740  603900354  373062864  333107271
  371594210  624026776  463406268  386041607  413106170  177200000
  621537519  481800873  370569774  223853736  359126022  369884651
  383257136  290835269  311950384  255185482  527965936  238539198
  436949634  759056935  355237933  358994850  347512318  726229501
  315156409  354825435  794881442  400063852  349546142  466625730
  252276927  448191819  327281779  316791257  306776732  216639112
  475186706  235956898  288383523  589580482  253625427  566652812
  167780960  369330363  528583774  616502912  330444045  569651467
  791217826  390493908  311605581  665692281  351692268  401847482
  352114312  317375031  307127625  234801895  493214993  325186032
  266892996  426074373  363258859  415484914  271457301  185991646
  877244782  201634991  431971116  374583879  524389083  774034007
  297372261  229930771  654855901  255614941  384919389  430051293
  343471816  270248367  191466556  296339528  278019771  329803958
  291420351  543934105  415933406  396592829  474009154  360366870
  339795890  333535934  298572799  375658750  273552592  346864886
  275650703  383930656  418765519  309460292  448906865  288885818
  269994119  433371112  242786137  302469017  270665134  251171807
  554987477  319715683  442299309  219922417  314178011  310650585
  321885765  358375603  163362095  269958228  227853986  490719763
  352616690  183348429  378882411  273144151  190539357  530438278
  287553595  226837760  353642274  353133898  321731527  207305509
  611257819  294456605  433514834  483866518  521170825  232372681
  255743093  563749323  374565754  277448382  419665568  346079773
  243240178  378410542  244721064  248639099  349464664  365971656
  297718711  258097122  300135367  376152455  231605150  427344325
  172855065  427374317  190538630  273339556  138545632  201585328
  225933435  278454417  325286646  349822765  582893671  320290989
  240685326  286801374  309492681  379014294  232325503  195745823
  314432837  201965915  202292902  246120986  154468902  264770996
  388156011  342463063  173965010  300451603  335062621  398479497
  246984278  497409852  485930816  342695435  164729679  414828246
  306209289  291465373  245285165  236412453  358372926  301913131
  319713881  498781117  274703340  272742922  341631208  285444603
  230685453  297002527  246233113  605425157  269755430  356296601
  249348933  273961019  262552893  229147509  414351546  262511490
  213525736  294805697  212902372  300473716  340487836  335802786
  216972543  173649931  180622424  467989645  247275374  236350661
  299288605  260095986  361832400  227927165  458863600]
[2069521700 2797501328 2847246203 1347597973 2048359754 1544455963
 2201647264 1670516444 1518815515 1332698830 1243089244 1662899439
 1005973645 1056057720 1074149279 1273576220 1028570942 1450026933
 1027082707  775398007 1402809540 1081142612  928760770  792910554
 1073394593 1128462972  865011746 1066179747 1063611805 1310466296
 1066970811  822824522 1214811252 1153337496  694394724  825025036
  962542945 1033928303  836303693 1281508100 1131927996  863756051
 1342321665  940352645  868390560 1146030912  788976453  612054506
  875458631  970766005  966554929  782836791  858848019 1050693953
 1515341399 1123794079  547426372  947495095 1024121104  755356711
  894983373 1159444662 1074419384 1148485886  880166924 1025468216
  773350147  678226133  873637528  701796444  746846894  785896609
  813367380  800059707  709709780  585796247 1016813075  790653942
  897690072  853983911  623933331  653779970  960996492  475106177
  817400891  654264015 1108569499 1017003568  934454096  698491347
  711025481  977043483  672806432  735099102  538375067  836836967
  942172396  829747654  745013115  668045518  579707738  896678241
  476684675  658344137  741847937  712205856  522657936  469310836
  723192705  512568819  634208384  743559645  487853320 1034800131
  879602366  757930663  631607053  471411300  345573032  714421503
  959007513  468060692  385680446  585410052  309208309  962182865
  586764305  543113985  411508343  574481229  589390539  797361618
  644136488  389925971  497375381 1104054072  461991867  296578797
  484592874  494471524  368744044  758411779 1045713802  752600867
  788680968  538983207  493311825  460435291  603873119  814044001
  746045700  429632142  441306145  677796076  618638999  657926987
  467365246  630162448  408247917  629443428  444100035  619179950
  347325802 1236005118  432233010  521311890  657869686  791657398
  459242249  443140005  441286195  424967620  549368315  556906378
  505703557  494879471  760006945  504050219  365352546  482349603
  910809311  622674139  746921274  631746197  546388108  436188866
  407711549  348840316  392924807  856085151  296938801  501138437
  473093228  381906762  456068181  807817888  626137675  694713380
  288467645  524028679  710644566  373661946  474968763  623726085
  644783140  426505244  312016928  520881154  708982323  540455876
  443280904  553709788  542358331  529323962  592462816  524976069
  391081192  880681519  449220945  381509870  384336108  474171806
  886686817  667094506  682716636  408430415  445135288  542063846
  331333876  559852396  485004754  375540831  396271103  527016307
  471222889  340952971  701729206  314215454  465380802  587235983
  543848418  552639571  487287646  184925486  287144079  424208848
  336567158  368875760  379631351  532950503  450717150  536414293
  374111707  328718434  275293450  302710615  368780809  449326618
  457696391  519311965  362211740  603900354  373062864  333107271
  371594210  624026776  463406268  386041607  413106170  177200000
  621537519  481800873  370569774  223853736  359126022  369884651
  383257136  290835269  311950384  255185482  527965936  238539198
  436949634  759056935  355237933  358994850  347512318  726229501
  315156409  354825435  794881442  400063852  349546142  466625730
  252276927  448191819  327281779  316791257  306776732  216639112
  475186706  235956898  288383523  589580482  253625427  566652812
  167780960  369330363  528583774  616502912  330444045  569651467
  791217826  390493908  311605581  665692281  351692268  401847482
  352114312  317375031  307127625  234801895  493214993  325186032
  266892996  426074373  363258859  415484914  271457301  185991646
  877244782  201634991  431971116  374583879  524389083  774034007
  297372261  229930771  654855901  255614941  384919389  430051293
  343471816  270248367  191466556  296339528  278019771  329803958
  291420351  543934105  415933406  396592829  474009154  360366870
  339795890  333535934  298572799  375658750  273552592  346864886
  275650703  383930656  418765519  309460292  448906865  288885818
  269994119  433371112  242786137  302469017  270665134  251171807
  554987477  319715683  442299309  219922417  314178011  310650585
  321885765  358375603  163362095  269958228  227853986  490719763
  352616690  183348429  378882411  273144151  190539357  530438278
  287553595  226837760  353642274  353133898  321731527  207305509
  611257819  294456605  433514834  483866518  521170825  232372681
  255743093  563749323  374565754  277448382  419665568  346079773
  243240178  378410542  244721064  248639099  349464664  365971656
  297718711  258097122  300135367  376152455  231605150  427344325
  172855065  427374317  190538630  273339556  138545632  201585328
  225933435  278454417  325286646  349822765  582893671  320290989
  240685326  286801374  309492681  379014294  232325503  195745823
  314432837  201965915  202292902  246120986  154468902  264770996
  388156011  342463063  173965010  300451603  335062621  398479497
  246984278  497409852  485930816  342695435  164729679  414828246
  306209289  291465373  245285165  236412453  358372926  301913131
  319713881  498781117  274703340  272742922  341631208  285444603
  230685453  297002527  246233113  605425157  269755430  356296601
  249348933  273961019  262552893  229147509  414351546  262511490
  213525736  294805697  212902372  300473716  340487836  335802786
  216972543  173649931  180622424  467989645  247275374  236350661
  299288605  260095986  361832400  227927165  458863600]
[2069521700 2797501328 2847246203 1347597973 2048359754 1544455963
 2201647264 1670516444 1518815515 1332698830 1243089244 1662899439
 1005973645 1056057720 1074149279 1273576220 1028570942 1450026933
 1027082707  775398007 1402809540 1081142612  928760770  792910554
 1073394593 1128462972  865011746 1066179747 1063611805 1310466296
 1066970811  822824522 1214811252 1153337496  694394724  825025036
  962542945 1033928303  836303693 1281508100 1131927996  863756051
 1342321665  940352645  868390560 1146030912  788976453  612054506
  875458631  970766005  966554929  782836791  858848019 1050693953
 1515341399 1123794079  547426372  947495095 1024121104  755356711
  894983373 1159444662 1074419384 1148485886  880166924 1025468216
  773350147  678226133  873637528  701796444  746846894  785896609
  813367380  800059707  709709780  585796247 1016813075  790653942
  897690072  853983911  623933331  653779970  960996492  475106177
  817400891  654264015 1108569499 1017003568  934454096  698491347
  711025481  977043483  672806432  735099102  538375067  836836967
  942172396  829747654  745013115  668045518  579707738  896678241
  476684675  658344137  741847937  712205856  522657936  469310836
  723192705  512568819  634208384  743559645  487853320 1034800131
  879602366  757930663  631607053  471411300  345573032  714421503
  959007513  468060692  385680446  585410052  309208309  962182865
  586764305  543113985  411508343  574481229  589390539  797361618
  644136488  389925971  497375381 1104054072  461991867  296578797
  484592874  494471524  368744044  758411779 1045713802  752600867
  788680968  538983207  493311825  460435291  603873119  814044001
  746045700  429632142  441306145  677796076  618638999  657926987
  467365246  630162448  408247917  629443428  444100035  619179950
  347325802 1236005118  432233010  521311890  657869686  791657398
  459242249  443140005  441286195  424967620  549368315  556906378
  505703557  494879471  760006945  504050219  365352546  482349603
  910809311  622674139  746921274  631746197  546388108  436188866
  407711549  348840316  392924807  856085151  296938801  501138437
  473093228  381906762  456068181  807817888  626137675  694713380
  288467645  524028679  710644566  373661946  474968763  623726085
  644783140  426505244  312016928  520881154  708982323  540455876
  443280904  553709788  542358331  529323962  592462816  524976069
  391081192  880681519  449220945  381509870  384336108  474171806
  886686817  667094506  682716636  408430415  445135288  542063846
  331333876  559852396  485004754  375540831  396271103  527016307
  471222889  340952971  701729206  314215454  465380802  587235983
  543848418  552639571  487287646  184925486  287144079  424208848
  336567158  368875760  379631351  532950503  450717150  536414293
  374111707  328718434  275293450  302710615  368780809  449326618
  457696391  519311965  362211740  603900354  373062864  333107271
  371594210  624026776  463406268  386041607  413106170  177200000
  621537519  481800873  370569774  223853736  359126022  369884651
  383257136  290835269  311950384  255185482  527965936  238539198
  436949634  759056935  355237933  358994850  347512318  726229501
  315156409  354825435  794881442  400063852  349546142  466625730

In [67]:
actor_ls = []
hold_ls = []
ws_ls = []
filmindex = -1

hold_gross = data_df["World Sales"].values

for film in data_df["Headlining Actor(s)"]:
    actnum = 0
    filmindex = filmindex + 1
    hold_ls = film.split(", ")
    for actor in hold_ls:
        actor_ls.append(actor)
        actnum = actnum + 1
        for i in range (1, actnum):
            ws_ls.append(hold_gross[filmindex])
        
        
actor_df = pd.DataFrame()
actor_df['Actor Name'] = actor_ls
actor_df['World Sales for Film'] = ws_ls
actor_df.head(12)

           Actor Name  World Sales for Film
0        Daisy Ridley            2069521700
1         John Boyega            2069521700
2         Oscar Isaac            2069521700
3   Robert Downey Jr.            2797501328
4         Chris Evans            2797501328
5        Mark Ruffalo            2797501328
6     Sam Worthington            2847246203
7         Zoe Saldana            2847246203
8    Sigourney Weaver            2847246203
9    Chadwick Boseman            1347597973
10  Michael B. Jordan            1347597973
11     Lupita Nyong'o            1347597973

In [68]:
act_df = actor_df.groupby("Actor Name").agg(world_sales_sum=('World Sales for Film','sum'),world_sales_mean=('World Sales for Film','mean'),total_number_films=('World Sales for Film','count'))    

act_df = act_df.rename(columns={'world_sales_sum':"World Sales Sum", 'world_sales_mean':"World Sales Mean", 'total_number_films':"Total Number of Films in Top 1000"})
act_sum_df = act_df.sort_values(by=['World Sales Sum'], ascending=False)
act_mean_df = act_df.sort_values(by=['World Sales Mean'], ascending=False)
act_num_df = act_df.sort_values(by=['Total Number of Films in Top 1000'], ascending=False)


pd.options.display.float_format = '{:.2f}'.format

In [69]:
act_sum_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Actor Name,,,
Robert Downey Jr.,13293408484,1208491680.36,11
Chris Evans,8602596671,1075324583.88,8
Dwayne Johnson,8466810975,769710088.64,11
Daniel Radcliffe,7786446940,973305867.50,8
Rupert Grint,7786446940,973305867.50,8
Vin Diesel,7481465894,748146589.40,10
Tom Hanks,7046907090,542069776.15,13
Ian McKellen,6971795253,871474406.62,8
Emma Watson,6769633865,967090552.14,7
Mark Ruffalo,6663022168,1665755542.00,4

In [70]:
act_mean_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Actor Name,,,
Billy Zane,2201647264,2201647264.00,1
Ty Simpkins,1670516444,1670516444.00,1
Sam Worthington,3340461196,1670230598.00,2
Mark Ruffalo,6663022168,1665755542.00,4
Oscar Isaac,3143670979,1571835489.50,2
Zendaya,1544455963,1544455963.00,1
John Boyega,4476369809,1492123269.67,3
Daisy Ridley,4476369809,1492123269.67,3
Bryce Dallas Howard,2980982740,1490491370.00,2
Josh Gad,1450026933,1450026933.00,1

In [71]:
act_num_df.head(10)

,World Sales Sum,World Sales Mean,Total Number of Films in Top 1000
Actor Name,,,
Tom Hanks,7046907090,542069776.15,13
Will Smith,6461645730,497049671.54,13
Tom Cruise,5593226273,466102189.42,12
Dwayne Johnson,8466810975,769710088.64,11
Robert Downey Jr.,13293408484,1208491680.36,11
Harrison Ford,5182242054,471112914.00,11
Hugh Jackman,4208505986,420850598.60,10
Vin Diesel,7481465894,748146589.40,10
Adam Sandler,3160469632,316046963.20,10
Ben Stiller,4417637516,490848612.89,9